#########################################################################################
#											#
#				Sort/Class Data Broker					#
#											#
#########################################################################################
#											#
#	Foo Lye Cheung			Sort Automation					#
#	04/11/2004				Penang					#
#											#
#	Check the WTU error log files.							#
#	If WTU fails to generated wafermap, email will be send to IT with 		#
#	the error message.								#
#	The purpose of this script is to monitor the BLS fails to trigger WTU		#
#	and alarm the IT to investigate the why WTU fail.				#
#	Scheduler runs at 3 every minutes and check for last 3 minutes old WTU error	#
#	log files.									#
#											#
#	NOTES										#
#	Requires Perl5 and Net::SMTP to run.						#
#											#
#########################################################################################

use Net::SMTP;

# Main code starts here
&WTUErrorLogChecking();

sub WTUErrorLogChecking
{
	my $WTUErrorLogDir = "C:\\Perl\\Programs\\Logs\\";
	
	print "Start WTU Error Log File checking...\n";
	chdir $WTUErrorLogDir || die "Cannt open $WTUErrorLogDir : $!\n";

	foreach my $ErrorLogFile (<*Error*.log>)
	{
		my $WTUFail = time - (stat($ErrorLogFile))[9];

		# Check for last 3 minute old WTU error log file
		if ($WTUFail <=180)
		{
			my $TodayDate = &Date();
			my $ErrorDate = $1 if ($ErrorLogFile =~ /^WTU_Error_(\d{8}).log$/);

			if ($ErrorDate >= $TodayDate)
			{
				my $ErrorLine;
				my $Now = localtime(time);

				print "$ErrorLogFile fails at $WTUFail seconds from now...\n"; 

				open (ERRORLOG, $ErrorLogFile) || die "Cannt open $ErrorLogFile : $!\n";
				while (<ERRORLOG>)
				{
					$ErrorLine .= $_;
				}
				close ERRORLOG;

				#my @To = ('lye.cheung.foo@intel.com', "david.ch'ng\@intel.com", 'ching.tatt.teoh@intel.com', 'seong.ngok.koo@intel.com', 'shi.ling.tan@intel.com', 'ee.chuangx.choong@intel.com', 'kai.jiunnx.loi@intel.com');
				@To = ('lye.cheung.foo@intel.com');
				my $Subject = "Wafermap unable to be generated by WTU - $Now\n";
				my $Body = "\n$ErrorLine\n";

				#&SendMail($Subject, $Body, @To);
		
			}
		}
	}	
	print "Finish WTU Error Log File checking...\n";
}

# Format the date so that match WTU error log
sub Date
{
	my ($SS, $MI, $HH, $DD, $MM, $YYYY) = localtime(time);

	$YYYY += 1900;
	$MM++;
	$MM =~ s/^(\d)$/0$1/;
	$DD =~ s/^(\d)$/0$1/;

	my $Date = $YYYY.$MM.$DD;
	return ($Date);
}

# Send mail to IT so that they when the BLS fails to trigger WTU
sub SendMail 
{
	my($Subject, $Body, @To) = @_;
	my $MailHost = 'mail.intel.com';
	my $From = 'SCDataBroker@intel.com';
	my $Tos = join('; ', @To);
	my $smtp = Net::SMTP->new($MailHost);
	$smtp->mail($From);
	$smtp->to(@To);
	$smtp->data();
	$smtp->datasend("To: $Tos\n");
	$smtp->datasend("Subject: $Subject\n");
	$smtp->datasend("$Body\n");
	$smtp->dataend();
	$smtp->quit();
}
